Update README with more info
kinvolk/cgnet pull request #14
Opened 2017-07-26 16:48 UTC by robertgzr

2017-07-27 09:30 UTC, alban requested changes
I'd add example how to compile it and use it:

```
$ make
$ ./cgnet top
$ kubectl apply -f ... 
...
```

2017-07-27 09:30 UTC, alban commented on README.md
> +Using eBPF to gather network statistics from cgroups.
I would say `s/Using/cgnet uses/`

2017-07-31 10:31 UTC, robertgzr commented
updated.

2017-07-31 12:24 UTC, alban approved these changes

2017-08-01 14:36 UTC, merged